[FEATURE] executa um comando do .env quando um evento e chamado
jasondavindev/live-reload-go pull request #14
Opened 2020-10-02 02:10 UTC by NicolasFujisawa

#7

2020-10-02 12:36 UTC, jasondavindev commented on .env.example
> +COMMAND=echo builda o projeto voce ai
deixa isso vazio

2020-10-02 12:36 UTC, jasondavindev commented on domain/command.go
> +// ExecuteCommand executa um comando no shell da maquina
De preferencia códigos/comentários em english

2020-10-02 12:37 UTC, jasondavindev commented on domain/command.go
> +		log.Println(err.Error())
Melhor lançar um log.Fatal pra interromper a aplicação, porque se não conseguiu executar o comando shell algo deve estar errado.

2020-10-02 12:41 UTC, jasondavindev requested changes

2020-10-02 12:41 UTC, jasondavindev commented on domain/enviroment.go
> +}
Primeiro: tu pode dar um nome melhor pro dominio. `environment` não está muito condizente. Pode ser `executor`.
Segundo: toda vez que passa por essa função a aplicação tem que recuperar a variavel do SO. Sugiro criar uma variável "estática" pra guardar o valor na primeira chamada e nas seguintes, retornar o valor guardado.

2020-10-02 14:15 UTC, toledompm reviewed
Depois de fazer as alterações me chama pra te ajudar a resolver os conflitos, meu pr fez umas alterações no  .env :s

2020-10-03 00:26 UTC, NicolasFujisawa commented on .env.example
> +COMMAND=echo builda o projeto voce ai
Done.

2020-10-03 00:26 UTC, NicolasFujisawa commented on domain/enviroment.go
> +}
Done.

2020-10-03 01:14 UTC, toledompm approved these changes
lgtm

2020-10-03 17:22 UTC, jasondavindev approved these changes

2020-10-03 17:23 UTC, merged